update acorn dependency
so that it works on things like this:

      $.each(data_points, function() {
        var date = new Date();
        date.setTime(this[0]);
        rows.push(
          //this ends up being [(a date), (the number of pageViews on that date), "an annotation tile, (if any)", ""]
          [date, this[1], undefined, undefined]
        )
      });

which would throw this when run on node 6 before:
/Users/ryan/code/canvas-lms/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:945
  throw err;
        ^
SyntaxError: The keyword 'undefined' is reserved (276:21)

see: https://github.com/ternjs/acorn/issues/361